# Generated by Django 5.0.1 on 2024-01-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participantID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField()),
                ('studentid', models.CharField(max_length=255)),
                ('universityname', models.CharField(max_length=255)),
                ('contestname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantCard',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('issuedate', models.DateField()),
                ('validitystatus', models.CharField(max_length=255)),
                ('Participants_participantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participants')),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificateID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('certificateText', models.CharField(max_length=255)),
                ('issuedate', models.DateField()),
                ('Participants_participantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participants')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('AttendenceID', models.AutoField(primary_key=True, serialize=False)),
                ('eventdate', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('Participants_participantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participants')),
            ],
        ),
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('QRcodeId', models.AutoField(primary_key=True, serialize=False)),
                ('QRcodetype', models.CharField(max_length=255)),
                ('OTP', models.CharField(max_length=255)),
                ('confirmationstatus', models.CharField(max_length=255)),
                ('Participants_participantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participants')),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('RegistrationID', models.AutoField(primary_key=True, serialize=False)),
                ('registrationdate', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('Participants_participantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participants')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('passwordhash', models.CharField(max_length=255)),
                ('Participants_ParticipantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participants')),
            ],
        ),
    ]
