# Generated by Django 5.0.1 on 2024-01-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='Participants_participantID',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='studentid',
            new_name='attendanceStatus',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='Participants_ParticipantID',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='participants',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
