<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-24 15:22
=======
# Generated by Django 5.0.1 on 2024-01-20 11:36
>>>>>>> 465f806336bb6f32cc3489e11679f2b3e478a457

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='Participants_participantID',
        ),
<<<<<<< HEAD
        migrations.RemoveField(
            model_name='participants',
            name='studentid',
=======
        migrations.RenameField(
            model_name='participants',
            old_name='studentid',
            new_name='attendanceStatus',
>>>>>>> 465f806336bb6f32cc3489e11679f2b3e478a457
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='Participants_ParticipantID',
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='participants',
            name='attendanceStatus',
            field=models.CharField(default='absent', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='abc@example.com', max_length=254),
            preserve_default=False,
=======
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
>>>>>>> 465f806336bb6f32cc3489e11679f2b3e478a457
        ),
        migrations.AlterField(
            model_name='participants',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='participants',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
