# Generated by Django 5.0.1 on 2024-01-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='Participants_participantID',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='Participants_ParticipantID',
        ),
        migrations.AddField(
            model_name='participants',
            name='attendanceStatus',
            field=models.CharField(default='absent', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='abc@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participants',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='participants',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
