# Generated by Django 5.0.1 on 2024-01-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_registrations_participants_participantid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='OTP',
            new_name='QRcode1',
        ),
        migrations.RenameField(
            model_name='qrcode',
            old_name='QRcodetype',
            new_name='QRcode2',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='confirmationstatus',
        ),
        migrations.AlterField(
            model_name='participants',
            name='attendanceStatus',
            field=models.CharField(default='A', max_length=255),
        ),
    ]
