# Generated by Django 5.0.1 on 2024-01-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_otp_qrcode_qrcode1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='QRcode1',
            new_name='DataQRcode1',
        ),
        migrations.RenameField(
            model_name='qrcode',
            old_name='QRcode2',
            new_name='DataQRcode2',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image_qr1',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image_qr2',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
