# Generated by Django 5.0.1 on 2024-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_qrcode1_qrcode_dataqrcode1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image_qr1',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image_qr2',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
