# Generated by Django 5.0.1 on 2024-01-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_qrcode_image_qr1_alter_qrcode_image_qr2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='age',
            field=models.CharField(max_length=3),
        ),
    ]
