# Generated by Django 5.0.1 on 2024-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_participants_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image_qr1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image_qr2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
