# Generated by Django 5.0.1 on 2024-01-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_qrcode_image_qr1_alter_qrcode_image_qr2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image_qr1',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image_qr2',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
