# Generated by Django 5.0.1 on 2024-03-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_participants_age_alter_qrcode_image_qr1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='age',
        ),
        migrations.AddField(
            model_name='participants',
            name='cnic',
            field=models.CharField(default='', max_length=13, unique=True),
        ),
    ]
