# Generated by Django 5.0.1 on 2024-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_participants_age_participants_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='cnic',
            field=models.CharField(default='', max_length=13),
        ),
    ]
