# Generated by Django 5.0.1 on 2024-03-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_participants_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='members',
            field=models.IntegerField(default=1),
        ),
    ]
