# Generated by Django 5.0.1 on 2024-03-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_participants_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='firstname',
            new_name='leadername',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='lastname',
        ),
    ]
