# Generated by Django 5.0.1 on 2024-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_rename_firstname_participants_leadername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='leadername',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='participants',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
